# SELECT A.AUTHOR_ID,	B.AUTHOR_NAME, A.CATEGORY, SUM(C.SALES * A.PRICE) AS TOTAL_SALES
# FROM BOOK A 
# JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID 
# JOIN BOOK_SALES C ON A.BOOK_ID = C.BOOK_ID
# WHERE LEFT(SALES_DATE, 7) = '2022-01'
# GROUP BY A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, C.SALES_DATE
# ORDER BY A.AUTHOR_ID, A.CATEGORY DESC

SELECT A.AUTHOR_ID,	B.AUTHOR_NAME, A.CATEGORY, SUM(C.SALES * A.PRICE) AS TOTAL_SALES
FROM BOOK A 
JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID 
JOIN BOOK_SALES C ON A.BOOK_ID = C.BOOK_ID
WHERE LEFT(SALES_DATE, 7) = '2022-01'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY A.AUTHOR_ID, A.CATEGORY DESC