-- 코드를 입력하세요
SELECT HISTORY_ID, CAR_ID, LEFT(START_DATE, 10), LEFT(END_DATE, 10), IF(DATEDIFF(END_DATE, START_DATE)+1 >= 30, '장기 대여',  '단기 대여') AS 'RENT_TYPE'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE YEAR(START_DATE) = '2022' AND MONTH(START_DATE) = '9'
ORDER BY HISTORY_ID DESC;